name:                path-calculator
version:             0.1.0.0
github:              "auroq/path-calculator"
license:             MIT
author:              "Parker Johansen"
maintainer:          "johansen.parker@gmail.com"
copyright:           "Copyright (c) 2020 Parker Johansen"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
category:            Text

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/auroq/path-calculator#readme>

dependencies:
- base >= 4.7 && < 5
- hspec
- validity
- genvalidity
- genvalidity-hspec


library:
  source-dirs: src

tests:
  path-calculator-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - path-calculator

